### ISSUE TITLE
adding a more friendly design

### ISSUE THREAD

**Issue by tb619tev** [jaapb/moab#1]
hey I'm interested in working with you on this project, create job so far we and improve the user interface by adding a model design to the ui

**Comment by OleninsHelvijs** [comment]
I would like to take part in this as well. I would like to add more interactive UI and possibly change/update error messages and the way how they are shown on the webpage for example when username and password are misspelt etc.

**Comment by jaapb** [comment]
Okay - you probably want to have a look at Ocsigen tutorials (http://ocsigen.org) before you start doing proper stuff. About the issue of error messages, please note that the fact that they are not informative is a feature, not a bug: for security purposes, you don't want to give information away (such as when a username is correct, but the password isn't) so the error messages are intended to be non-specific.

**Comment by OleninsHelvijs** [comment]
Thanks Jaapb for clarification. I will take a look in Ocsigen tutorials . 

> About the issue of error messages, please note that the fact that they are not informative is a feature, not a bug: for security purposes, you don't want to give information away (such as when a username is correct, but the password isn't) so the error messages are intended to be non-specific.

I definitely agree with you about that. Apologies for misunderstanding created, I did not state my idea clearly.  

![untitled](https://user-images.githubusercontent.com/32101902/33018278-a61ceb70-cded-11e7-8ae3-360febf01540.png)
As you can see in the picture above , Message prompted is kind a "Plain". 
What I was thinking is not to change the message it self but change the appearance on it. For example Error message displayed in red colour and a bit bigger letters and displayed in behind the User ID and PW text-boxes. 

Idea for this was, because, if the UI changes to something , let's say more colourful and interactive as @tb619tev is suggesting, then Messages displayed should be adjusted as well to possibly match the same style of the possible UI.

**Comment by jaapb** [comment]
OK, thanks for clarifying. I look forward to receiving your pull requests.

**Comment by OleninsHelvijs** [comment]
I have checked quite a lot of tutorials and videos of "_How to do ... for dummies_"  
Is there a way to remotely connect to your server and take a look at the things there or only way to participate is to get my own Linux OS and install Ocsigen to play around?  

Also, could you please create a label "Awaiting clarification" which I could add to issue whenever I need a clarification from @jaapb? This would serve a purpose of - Whenever I comment a question I can add this label. And when a question is answered then the person who answered it can remove it?

**Comment by ArunRic** [comment]
@Helvijs-t2t Remote connection credentials to the server won't be given. Using VirtualBox you can install a Linux distro and play around, I'm not sure if anyone has been able to run test.byte on moab, but ocsigen-start works fine.

**Comment by jaapb** [comment]
I have created a VirtualBox image with an Ubuntu installation that contains a working version of Moab - can share that on request to anyone with a Middlesex account.
